type: object
required:
  - api_host
  - api_prefix
  - map_shard
  - map_dx
  - map_dy
  - map_size_x
  - map_size_y
properties:
  api_host:
    type: string
  api_prefix:
    type: ["string", "null"]
  api_token:
    type: ["string", "null"]
  api_username:
    type: ["string", "null"]
  api_password:
    type: ["string", "null"]
  api_secure:
    type: ["boolean", "null"]
  map_shard:
    type: string
  map_description:
    type: ["string", "null"]
  map_dx:
    type: array
  map_dy:
    type: array
  map_size_x:
    type: array
  map_size_y:
    type: array
  save_results_filename:
    type: ["string", "null"]
  progress_bar:
    type: boolean
