type: object
required:
  - api_host
  - api_prefix
  - map_shard
properties:
  api_host:
    type: string
  api_prefix:
    type: string
  api_token:
    type: ["string", "null"]
  api_username:
    type: ["string", "null"]
  api_password:
    type: ["string", "null"]
  api_secure:
    type: ["boolean", "null"]
  map_shard:
    type: string
  map_description:
    type: ["string", "null"]
  save_results_filename:
    type: ["string", "null"]
  progress_bar:
    type: boolean
